site_name: 'Windmill Dark MkDocs Theme'
site_description: 'MkDocs theme focused on navigation and usability.'
site_author: 'Alexandre ZANNI'

repo_url: https://github.com/noraj/mkdocs-windmill-dark

theme:
    name: null
    custom_dir: mkdocs_windmill_dark
    # default from mkdocs_theme.yml
    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: true
    history_buttons: true
    article_nav_top: true
    article_nav_bottom: true

nav:
  - Ana Sayfa: home.md
  - Bölüm 1:
      - Güvenlik Duvari: mainpage.md
      - Port Filtreleme: port.md
      - Protokol Filtreleme: protokol.md
      - İzin Tabanlı Filtreleme: izin_tabanli.md
      - Akıllı Filtreleme: smart_filter.md
      - Güvenlik Duvari Türleri: types.md
      - Güvenlik Duvari Seçimi: choice.md
  - Bölüm 2:
      - IDS/IPS Nedir? : ids.md
      - IDS/IPS Sistemlerinin Seçimi Ve Bakımı: ips_choice_care.md
      - IDS/IPS Sistemlerinin Türleri: ips_type.md
  - Bölüm 3:
      - Antivirüs Nedir?: antivirus.md
      - Antivirüs Sistemlerinin Avantaj ve Dezavantajları: proscons.md
  - Bölüm 4:
      - Kriptografi Nedir? : crypto.md
  - Bölüm 5:
      - Kaynaklar: sources.md

markdown_extensions:
    - toc:
        permalink: '#'

extra:
    version: 0.1.4
